services:
  traefik:
    image: traefik:3
    ports:
      - "8080:80"       # Web
      - "8081:8080"     # Dashboard
    volumes:
      - ${HOST_WORKSPACE_FOLDER}/examples/local/traefik:/etc/traefik
      - ${HOST_WORKSPACE_FOLDER}:/plugins-local/src/github.com/you/traefik-plugin-hello:rw
      # ⬇️ Docker socket so Traefik can read container labels
      - /var/run/docker.sock:/var/run/docker.sock:ro
  whoami:
    image: traefik/whoami:v1.11
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.who.loadbalancer.server.port=80"
      - "traefik.http.routers.who.rule=Host(`demo.localhost`)"
      - "traefik.http.routers.who.entrypoints=web"
      - "traefik.http.routers.who.middlewares=my-plugin@file"
