api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    # http:
    #   middlewares:
    #     - my-plugin@file

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

experimental:
  localPlugins:
    hello:
      moduleName: github.com/you/traefik-plugin-hello  # entspricht Ordner unter plugins-local/src

log:
  level: DEBUG
